# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(unique_for_date='publish_date', verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20, verbose_name='status')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish date')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='modify date')),
                ('comment_enable', models.BooleanField(default=True, verbose_name='comment enable')),
            ],
            options={
                'db_table': 'blog_articles',
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'get_latest_by': 'publish_date',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['title'],
                'db_table': 'blog_categories',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('contact_date', models.DateTimeField(auto_now_add=True, verbose_name='contact date')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-contact_date'],
                'db_table': 'blog_message',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['title'],
                'db_table': 'blog_tags',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.Category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='tags'),
        ),
    ]
